#!/bin/bash
set -xe
DEVUID=${DEVUID:-1000}
DEVGID=${DEVGID:-1000}
rm /dev/random
cp -a /dev/urandom /dev/random;
groupadd -g ${DEVGID} developer
useradd -u ${DEVUID} -g ${DEVGID} -G sudo -d /home/developer developer
mkdir -p /home/developer
chown ${DEVUID}:${DEVGID} /home/developer
if [ ! -d /home/developer/.m2 ]
then
    cp -r /root/.m2 /home/developer 
    chown -R developer.developer /home/developer
    echo "source prepare" >/home/developer/.bashrc
fi

. /usr/local/toolchain/tools/environment

export BRANCH=$(getbranch)
export BUILD_NUMBER=0
export HOME=/home/developer
exec sudo -E -u developer env "PATH=$PATH" "$@"
