#!/bin/bash
set -xe

rm /dev/random
cp -a /dev/urandom /dev/random;
groupadd -g ${DEVGID} developer
useradd -u ${DEVUID} -g ${DEVGID} -G sudo -d /home/developer developer
chown ${DEVUID}:${DEVGID} /home/developer
if [ ! -d /home/developer/.m2 ]
then
    cp -r /root/.m2 /home/developer 
    chown -R developer.developer /home/developer
fi

export DISPLAY=:0
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export HOME=/home/developer
export PATH=$PATH:/usr/local/toolchain/tools
exec sudo -E -u developer env "PATH=$PATH" "$@"
