#!/bin/bash
normalized_branch=$(echo $HEAD_BRANCH|sed 'sA[/_]A.Ag')
repo_uri="https://repo.kodekonveyor.com/$REPO_NAME/$(echo $PULL_REQUEST_REPO_FULL_NAME |sed 'sA/.*AA')/$normalized_branch"
echo  "building pull request. Documentation creation are not executed."
echo  "Documentation is at $repo_uri"
mkdir -p $MODEL_BASENAME
echo "<html><head><title>Relevant docs</title></head><body>" >$MODEL_BASENAME/index.html
echo "<a href=\"$repo_uri\">Documentation</a>" >>$MODEL_BASENAME/index.html
echo "</body></html>" >>$MODEL_BASENAME/index.html
