#!/bin/bash
repo=$(git remote -v|grep "origin.*fetch"|sed 'sA^.*github.com/AA;sA/.*AA')
rsync -e "ssh -p 22022" -ar shippable/ shippable@repo.kodekonveyor.com:/var/www/adadocs/PDEngine/$repo/$BUILD_NUMBER
normalized_branch=$(echo $BRANCH|sed 'sA[/_]A.Ag')
ln -s $BUILD_NUMBER $normalized_branch
rsync -e "ssh -p 22022" -a $normalized_branch shippable@kodekonveyor.com:/var/www/adadocs/PDEngine/$repo

