#!/bin/bash
set -xe
. /usr/local/toolchain/tools/environment
if [ $IS_PULL_REQUEST = true ]
    echo "not deploying pull request build"
    exit
fi
if [ -f .mutmut-cache ]
then
    mv -f .mutmut-cache shippable
fi
export repo=$(git remote -v|grep "origin.*fetch"|sed 'sA^.*github.com/AA;sA/.*AA;s/^.*://')
export project=$(git remote -v|grep "origin.*fetch"|sed 'sA.*/AA;sA.git.*AA')

normalized_branch=$(echo $BRANCH|sed 'sA[/_]A.Ag')
rmcommand="cd /$project/$repo\n-rm $normalized_branch"
echo -e "$rmcommand" | sftp -b- -oPort=22022 r_$repo@repository.kodekonveyor.com
linkcommand="ln -s $BUILD_NUMBER $normalized_branch"
echo -e "cd /$project/$repo\nput -r shippable $BUILD_NUMBER\n$linkcommand" | sftp -b- -oPort=22022 r_$repo@repository.kodekonveyor.com

if [ -n "${GIT_TAG}" ]
then
	make publish_release
fi
