#!/bin/bash
set -xe
. /usr/local/toolchain/tools/environment
if [ -f .mutmut-cache ]
then
    mv -f .mutmut-cache shippable
fi
export repo=$(git remote -v|grep "origin.*fetch"|sed 'sA^.*github.com/AA;sA/.*AA;s/^.*://')
export project=$(git remote -v|grep "origin.*fetch"|sed 'sA.*/AA;sA.git.*AA')
rsync -e "ssh -p 22022" -ar shippable/ shippable@repo.kodekonveyor.com:/var/www/repo/$project/$repo/$BUILD_NUMBER
normalized_branch=$(echo $BRANCH|sed 'sA[/_]A.Ag')
ln -s $BUILD_NUMBER $normalized_branch
rsync -e "ssh -p 22022" -a $normalized_branch shippable@repo.kodekonveyor.com:/var/www/repo/$project/$repo

if [ -n "${GIT_TAG}" ]
then
	make publish_release
fi
